### ISSUE TITLE
the so file 'libc++_shared.so' is located in the libs folder, while doesn't exist when running project

### ISSUE THREAD

**Issue by leverage2009lvt** [mshockwave/PdfiumAndroid#13]
09-13 16:08:00.816 19943-19943/com.shockwave.pdfiumtest E/com.shockwave.pdfium.PdfiumCore: Native libraries failed to load - java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shockwave.pdfiumtest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.shockwave.pdfiumtest-2/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libc++_shared.so"
09-13 16:08:00.816 19943-19943/com.shockwave.pdfiumtest D/com.shockwave.pdfium.PdfiumCore: Starting PdfiumAndroid 1.9.0
09-13 16:08:00.821 19943-19943/com.shockwave.pdfiumtest E/art: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
09-13 16:08:00.822 19943-19943/com.shockwave.pdfiumtest D/AndroidRuntime: Shutting down VM
09-13 16:08:00.824 19943-19943/com.shockwave.pdfiumtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.shockwave.pdfiumtest, PID: 19943
                                                                          java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
                                                                              at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                                              at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:135)
                                                                              at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:127)
                                                                              at com.shockwave.pdfiumtest.PdfActivity.onCreate(PdfActivity.java:128)
                                                                              at android.app.Activity.performCreate(Activity.java:6875)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:163)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6396)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by lovehahazy** [comment]
2018-11-14 16:19:20.155 6500-6500/com.qingtime.icare E/com.shockwave.pdfium.PdfiumCore: Native libraries failed to load - java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qingtime.icare-6rrrtIORNMlidDwcVDATXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.qingtime.icare-6rrrtIORNMlidDwcVDATXQ==/lib/arm64, /data/app/com.qingtime.icare-6rrrtIORNMlidDwcVDATXQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libmodpng.so"
2018-11-14 16:19:20.156 6500-6500/com.qingtime.icare E/zygote64: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
2018-11-14 16:19:20.158 6500-6500/com.qingtime.icare E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qingtime.icare, PID: 6500
    java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
        at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
        at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:133)
        at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:125)
        at com.qingtime.icare.widget.pdfsourse.FileSource.createDocument(FileSource.java:27)

**Comment by XCarbone** [comment]
any update on this ?

**Comment by mshockwave** [comment]
> any update on this ?

Hi, thanks for tracking this issue. Unfortunately I have left Android development for quite some time. So I don't have the right environment and up-to-date knowledge based to solve this issue right now

**Comment by KnIfER** [comment]
search for `android gradle ndk{}`, some filter need to be set.
